name: reusable-docker

on:
  workflow_call:
    inputs:
      image_name:
        type: string
        required: true
      tag:
        type: string
        required: true

    outputs:
      image_url:
        value: ${{ jobs.docker-reuseable.outputs.image_url }}

    secrets:
      docker_username:
        required: true
      docker_token:
        required: true

jobs:
  docker-reuseable:
    runs-on: ubuntu-latest
    outputs:
      image_url: ${{ steps.set-outputs.outputs.image_url }}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_token }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ inputs.image_name }}:${{ inputs.tag }}

      - name: Define outputs
        id: set-outputs
        run: echo "image_url=${{ inputs.image_name }}:${{ inputs.tag }}" >> $GITHUB_OUTPUT
